import type {
  Market,
  Service,
  FillingCurve,
  Alert,
  AlertRule,
  AggressivenessConfig,
  DashboardKPIs,
  RevenueDataPoint,
  ServiceStatus,
  Cluster,
  CurveZoneConfig,
} from "@/types"

export const markets: Market[] = [
  {
    id: "bue-mdp",
    name: "Buenos Aires - Mar del Plata",
    origin: "Buenos Aires",
    destination: "Mar del Plata",
    distance: 400,
    avgDuration: "5h 30m",
    dailyServices: 32,
    currentOccupancy: 78,
    targetOccupancy: 75,
    revenue: 285000000,
    revenueTarget: 270000000,
    revenueUSD: 285000,
    revenueTargetUSD: 270000,
  },
  {
    id: "bue-cor",
    name: "Buenos Aires - Córdoba",
    origin: "Buenos Aires",
    destination: "Córdoba",
    distance: 700,
    avgDuration: "9h 00m",
    dailyServices: 24,
    currentOccupancy: 72,
    targetOccupancy: 74,
    revenue: 420000000,
    revenueTarget: 450000000,
    revenueUSD: 420000,
    revenueTargetUSD: 450000,
  },
  {
    id: "bue-ros",
    name: "Buenos Aires - Rosario",
    origin: "Buenos Aires",
    destination: "Rosario",
    distance: 300,
    avgDuration: "4h 00m",
    dailyServices: 28,
    currentOccupancy: 68,
    targetOccupancy: 72,
    revenue: 195000000,
    revenueTarget: 210000000,
    revenueUSD: 195000,
    revenueTargetUSD: 210000,
  },
  {
    id: "bue-mza",
    name: "Buenos Aires - Mendoza",
    origin: "Buenos Aires",
    destination: "Mendoza",
    distance: 1050,
    avgDuration: "13h 00m",
    dailyServices: 18,
    currentOccupancy: 82,
    targetOccupancy: 78,
    revenue: 520000000,
    revenueTarget: 480000000,
    revenueUSD: 520000,
    revenueTargetUSD: 480000,
  },
  {
    id: "bue-brc",
    name: "Buenos Aires - Bariloche",
    origin: "Buenos Aires",
    destination: "Bariloche",
    distance: 1600,
    avgDuration: "20h 00m",
    dailyServices: 12,
    currentOccupancy: 85,
    targetOccupancy: 80,
    revenue: 380000000,
    revenueTarget: 350000000,
    revenueUSD: 380000,
    revenueTargetUSD: 350000,
  },
  {
    id: "bue-neu",
    name: "Buenos Aires - Neuquén",
    origin: "Buenos Aires",
    destination: "Neuquén",
    distance: 1200,
    avgDuration: "14h 00m",
    dailyServices: 14,
    currentOccupancy: 71,
    targetOccupancy: 70,
    revenue: 290000000,
    revenueTarget: 285000000,
    revenueUSD: 290000,
    revenueTargetUSD: 285000,
  },
  {
    id: "bue-sfe",
    name: "Buenos Aires - Santa Fe",
    origin: "Buenos Aires",
    destination: "Santa Fe",
    distance: 475,
    avgDuration: "6h 00m",
    dailyServices: 16,
    currentOccupancy: 65,
    targetOccupancy: 70,
    revenue: 145000000,
    revenueTarget: 160000000,
    revenueUSD: 145000,
    revenueTargetUSD: 160000,
  },
  {
    id: "cor-mza",
    name: "Córdoba - Mendoza",
    origin: "Córdoba",
    destination: "Mendoza",
    distance: 650,
    avgDuration: "8h 00m",
    dailyServices: 10,
    currentOccupancy: 74,
    targetOccupancy: 72,
    revenue: 125000000,
    revenueTarget: 118000000,
    revenueUSD: 125000,
    revenueTargetUSD: 118000,
  },
]

export const clusters: Cluster[] = [
  {
    id: "cluster-1",
    name: "Todos los Viernes",
    type: "day-of-week",
    description: "Servicios que salen los días viernes",
    tags: ["viernes", "fin-de-semana"],
    marketId: "all",
    conditions: {
      daysOfWeek: [5],
    },
    isActive: true,
  },
  {
    id: "cluster-2",
    name: "Nocturnos (+18hs)",
    type: "time-of-day",
    description: "Servicios con salida después de las 18:00",
    tags: ["nocturno", "tarde"],
    marketId: "all",
    conditions: {
      timeRange: { start: "18:00", end: "23:59" },
    },
    isActive: true,
  },
  {
    id: "cluster-3",
    name: "Temporada Alta (Dic-Feb)",
    type: "season",
    description: "Servicios durante temporada alta de verano",
    tags: ["temporada-alta", "verano"],
    marketId: "all",
    conditions: {
      dateRange: { start: "12-01", end: "02-28" },
    },
    isActive: true,
  },
  {
    id: "cluster-4",
    name: "Temporada Ski (Jun-Sep)",
    type: "season",
    description: "Temporada de ski para Bariloche",
    tags: ["temporada-alta", "invierno", "ski"],
    marketId: "bue-brc",
    conditions: {
      dateRange: { start: "06-01", end: "09-30" },
    },
    isActive: true,
  },
  {
    id: "cluster-5",
    name: "Feriados Largos",
    type: "special",
    description: "Fines de semana largos y feriados nacionales",
    tags: ["feriado", "especial"],
    marketId: "all",
    conditions: {
      holidays: true,
    },
    isActive: true,
  },
  {
    id: "cluster-6",
    name: "Madrugadores (-10hs)",
    type: "time-of-day",
    description: "Servicios con salida antes de las 10:00",
    tags: ["mañana", "ejecutivo"],
    marketId: "all",
    conditions: {
      timeRange: { start: "05:00", end: "10:00" },
    },
    isActive: true,
  },
  {
    id: "cluster-7",
    name: "Fines de Semana",
    type: "day-of-week",
    description: "Sábados y Domingos",
    tags: ["fin-de-semana", "ocio"],
    marketId: "all",
    conditions: {
      daysOfWeek: [0, 6],
    },
    isActive: true,
  },
  {
    id: "cluster-8",
    name: "Costa Atlántica Verano",
    type: "season",
    description: "Mar del Plata en temporada alta",
    tags: ["playa", "verano", "temporada-alta"],
    marketId: "bue-mdp",
    conditions: {
      dateRange: { start: "12-15", end: "03-15" },
    },
    isActive: true,
  },
]

export const defaultZoneConfig: CurveZoneConfig = {
  tolerance: 5,
  zones: [
    {
      id: "ahead-3",
      name: "Muy adelante",
      level: 3,
      minDeviation: 15,
      maxDeviation: 100,
      color: "#059669", // emerald-600 (dark green)
      action: "Subir precio fuerte",
    },
    {
      id: "ahead-2",
      name: "Adelante",
      level: 2,
      minDeviation: 10,
      maxDeviation: 15,
      color: "#10b981", // emerald-500 (medium green)
      action: "Subir precio moderado",
    },
    {
      id: "ahead-1",
      name: "Levemente adelante",
      level: 1,
      minDeviation: 5,
      maxDeviation: 10,
      color: "#6ee7b7", // emerald-300 (light green)
      action: "Subir precio leve",
    },
    {
      id: "on-curve",
      name: "En curva",
      level: 0,
      minDeviation: -5,
      maxDeviation: 5,
      color: "#3b82f6", // blue-500
      action: "Mantener precio",
    },
    {
      id: "behind-1",
      name: "Levemente atrasado",
      level: -1,
      minDeviation: -10,
      maxDeviation: -5,
      color: "#fbbf24", // amber-400 (yellow)
      action: "Bajar precio leve",
    },
    {
      id: "behind-2",
      name: "Atrasado",
      level: -2,
      minDeviation: -15,
      maxDeviation: -10,
      color: "#f97316", // orange-500
      action: "Bajar precio moderado",
    },
    {
      id: "behind-3",
      name: "Muy atrasado",
      level: -3,
      minDeviation: -100,
      maxDeviation: -15,
      color: "#dc2626", // red-600
      action: "Bajar precio fuerte",
    },
  ],
}

// Helper to generate status based on gap
function getStatus(gap: number): ServiceStatus {
  if (gap >= 15) return "ahead-3"
  if (gap >= 10) return "ahead-2"
  if (gap >= 5) return "ahead-1"
  if (gap > -5) return "on-curve"
  if (gap > -10) return "behind-1"
  if (gap > -15) return "behind-2"
  return "behind-3"
}

export const services: Service[] = [
  // Buenos Aires - Mar del Plata (32 servicios diarios, mostramos varios)
  {
    id: "srv-001",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "06:00",
    arrivalTime: "11:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 8,
    totalSeats: 52,
    soldSeats: 42,
    currentOccupancy: 81,
    targetOccupancy: 55,
    currentPrice: 28500,
    basePrice: 25000,
    recommendedPrice: 35000,
    priceChange: 22.8,
    status: "ahead-3",
    gap: 26,
    bookingVelocity: 5.2,
    expectedVelocity: 3.1,
    revenueTotal: 1197000,
    revenueTotalUSD: 1197,
    comments: "Alta demanda verano",
    tags: ["temporada-alta", "promocionado"],
  },
  {
    id: "srv-002",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "08:00",
    arrivalTime: "13:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 6,
    totalSeats: 52,
    soldSeats: 35,
    currentOccupancy: 67,
    targetOccupancy: 55,
    currentPrice: 27000,
    basePrice: 25000,
    recommendedPrice: 30000,
    priceChange: 11.1,
    status: "ahead-2",
    gap: 12,
    bookingVelocity: 4.1,
    expectedVelocity: 3.1,
    revenueTotal: 945000,
    revenueTotalUSD: 945,
    comments: "",
    tags: ["temporada-alta"],
  },
  {
    id: "srv-003",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "10:30",
    arrivalTime: "16:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 4,
    totalSeats: 52,
    soldSeats: 31,
    currentOccupancy: 60,
    targetOccupancy: 55,
    currentPrice: 26000,
    basePrice: 25000,
    recommendedPrice: 28000,
    priceChange: 7.7,
    status: "ahead-1",
    gap: 5,
    bookingVelocity: 3.5,
    expectedVelocity: 3.1,
    revenueTotal: 806000,
    revenueTotalUSD: 806,
    comments: "",
    tags: [],
  },
  {
    id: "srv-004",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "14:00",
    arrivalTime: "19:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 3,
    totalSeats: 52,
    soldSeats: 28,
    currentOccupancy: 54,
    targetOccupancy: 55,
    currentPrice: 25000,
    basePrice: 25000,
    recommendedPrice: 25000,
    priceChange: 0,
    status: "on-curve",
    gap: -1,
    bookingVelocity: 3.0,
    expectedVelocity: 3.1,
    revenueTotal: 700000,
    revenueTotalUSD: 700,
    comments: "Sigue curva normal",
    tags: [],
  },
  {
    id: "srv-005",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "18:00",
    arrivalTime: "23:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 5,
    totalSeats: 52,
    soldSeats: 24,
    currentOccupancy: 46,
    targetOccupancy: 55,
    currentPrice: 24000,
    basePrice: 25000,
    recommendedPrice: 22000,
    priceChange: -8.3,
    status: "behind-1",
    gap: -9,
    bookingVelocity: 2.4,
    expectedVelocity: 3.1,
    revenueTotal: 576000,
    revenueTotalUSD: 576,
    comments: "",
    tags: ["revisar"],
  },
  {
    id: "srv-006",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "22:00",
    arrivalTime: "03:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 7,
    totalSeats: 52,
    soldSeats: 20,
    currentOccupancy: 38,
    targetOccupancy: 55,
    currentPrice: 23000,
    basePrice: 25000,
    recommendedPrice: 19000,
    priceChange: -17.4,
    status: "behind-2",
    gap: -17,
    bookingVelocity: 1.8,
    expectedVelocity: 3.1,
    revenueTotal: 460000,
    revenueTotalUSD: 460,
    comments: "Nocturno con baja demanda",
    tags: ["nocturno", "promocionar"],
  },
  // Buenos Aires - Córdoba
  {
    id: "srv-007",
    marketId: "bue-cor",
    marketName: "Buenos Aires - Córdoba",
    departureTime: "07:00",
    arrivalTime: "16:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 10,
    totalSeats: 48,
    soldSeats: 38,
    currentOccupancy: 79,
    targetOccupancy: 58,
    currentPrice: 42000,
    basePrice: 38000,
    recommendedPrice: 48000,
    priceChange: 14.3,
    status: "ahead-3",
    gap: 21,
    bookingVelocity: 4.8,
    expectedVelocity: 3.0,
    revenueTotal: 1596000,
    revenueTotalUSD: 1596,
    comments: "Coche cama vendiendo bien",
    tags: ["cama", "premium"],
  },
  {
    id: "srv-008",
    marketId: "bue-cor",
    marketName: "Buenos Aires - Córdoba",
    departureTime: "12:00",
    arrivalTime: "21:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 6,
    totalSeats: 48,
    soldSeats: 28,
    currentOccupancy: 58,
    targetOccupancy: 58,
    currentPrice: 38000,
    basePrice: 38000,
    recommendedPrice: 38500,
    priceChange: 1.3,
    status: "on-curve",
    gap: 0,
    bookingVelocity: 3.0,
    expectedVelocity: 3.0,
    revenueTotal: 1064000,
    revenueTotalUSD: 1064,
    comments: "",
    tags: [],
  },
  {
    id: "srv-009",
    marketId: "bue-cor",
    marketName: "Buenos Aires - Córdoba",
    departureTime: "20:00",
    arrivalTime: "05:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 14,
    totalSeats: 48,
    soldSeats: 44,
    currentOccupancy: 92,
    targetOccupancy: 58,
    currentPrice: 45000,
    basePrice: 38000,
    recommendedPrice: 55000,
    priceChange: 22.2,
    status: "ahead-3",
    gap: 34,
    bookingVelocity: 6.2,
    expectedVelocity: 3.0,
    revenueTotal: 1980000,
    revenueTotalUSD: 1980,
    comments: "Nocturno muy demandado",
    tags: ["nocturno", "cama", "top-seller"],
  },
  {
    id: "srv-010",
    marketId: "bue-cor",
    marketName: "Buenos Aires - Córdoba",
    departureTime: "23:30",
    arrivalTime: "08:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 8,
    totalSeats: 48,
    soldSeats: 18,
    currentOccupancy: 38,
    targetOccupancy: 58,
    currentPrice: 36000,
    basePrice: 38000,
    recommendedPrice: 30000,
    priceChange: -16.7,
    status: "behind-3",
    gap: -20,
    bookingVelocity: 1.5,
    expectedVelocity: 3.0,
    revenueTotal: 648000,
    revenueTotalUSD: 648,
    comments: "Competencia con avión",
    tags: ["revisar", "competencia-aerea"],
  },
  // Buenos Aires - Rosario
  {
    id: "srv-011",
    marketId: "bue-ros",
    marketName: "Buenos Aires - Rosario",
    departureTime: "06:30",
    arrivalTime: "10:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 3,
    totalSeats: 52,
    soldSeats: 40,
    currentOccupancy: 77,
    targetOccupancy: 60,
    currentPrice: 18500,
    basePrice: 16000,
    recommendedPrice: 21000,
    priceChange: 13.5,
    status: "ahead-2",
    gap: 17,
    bookingVelocity: 4.5,
    expectedVelocity: 3.2,
    revenueTotal: 740000,
    revenueTotalUSD: 740,
    comments: "Ejecutivos madrugadores",
    tags: ["ejecutivo", "morning-rush"],
  },
  {
    id: "srv-012",
    marketId: "bue-ros",
    marketName: "Buenos Aires - Rosario",
    departureTime: "09:00",
    arrivalTime: "13:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 2,
    totalSeats: 52,
    soldSeats: 32,
    currentOccupancy: 62,
    targetOccupancy: 60,
    currentPrice: 17000,
    basePrice: 16000,
    recommendedPrice: 17500,
    priceChange: 2.9,
    status: "on-curve",
    gap: 2,
    bookingVelocity: 3.3,
    expectedVelocity: 3.2,
    revenueTotal: 544000,
    revenueTotalUSD: 544,
    comments: "",
    tags: [],
  },
  {
    id: "srv-013",
    marketId: "bue-ros",
    marketName: "Buenos Aires - Rosario",
    departureTime: "14:00",
    arrivalTime: "18:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 4,
    totalSeats: 52,
    soldSeats: 22,
    currentOccupancy: 42,
    targetOccupancy: 60,
    currentPrice: 15000,
    basePrice: 16000,
    recommendedPrice: 12500,
    priceChange: -16.7,
    status: "behind-2",
    gap: -18,
    bookingVelocity: 2.0,
    expectedVelocity: 3.2,
    revenueTotal: 330000,
    revenueTotalUSD: 330,
    comments: "Horario difícil",
    tags: ["revisar"],
  },
  {
    id: "srv-014",
    marketId: "bue-ros",
    marketName: "Buenos Aires - Rosario",
    departureTime: "18:30",
    arrivalTime: "22:30",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 5,
    totalSeats: 52,
    soldSeats: 35,
    currentOccupancy: 67,
    targetOccupancy: 60,
    currentPrice: 17500,
    basePrice: 16000,
    recommendedPrice: 19000,
    priceChange: 8.6,
    status: "ahead-1",
    gap: 7,
    bookingVelocity: 3.8,
    expectedVelocity: 3.2,
    revenueTotal: 612500,
    revenueTotalUSD: 612,
    comments: "Regreso laboral",
    tags: ["ejecutivo"],
  },
  // Buenos Aires - Mendoza
  {
    id: "srv-015",
    marketId: "bue-mza",
    marketName: "Buenos Aires - Mendoza",
    departureTime: "08:00",
    arrivalTime: "21:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 15,
    totalSeats: 45,
    soldSeats: 40,
    currentOccupancy: 89,
    targetOccupancy: 62,
    currentPrice: 58000,
    basePrice: 52000,
    recommendedPrice: 68000,
    priceChange: 17.2,
    status: "ahead-3",
    gap: 27,
    bookingVelocity: 5.5,
    expectedVelocity: 2.8,
    revenueTotal: 2320000,
    revenueTotalUSD: 2320,
    comments: "Turismo enológico",
    tags: ["cama", "premium", "turismo"],
  },
  {
    id: "srv-016",
    marketId: "bue-mza",
    marketName: "Buenos Aires - Mendoza",
    departureTime: "18:00",
    arrivalTime: "07:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 12,
    totalSeats: 45,
    soldSeats: 38,
    currentOccupancy: 84,
    targetOccupancy: 62,
    currentPrice: 55000,
    basePrice: 52000,
    recommendedPrice: 62000,
    priceChange: 12.7,
    status: "ahead-3",
    gap: 22,
    bookingVelocity: 5.0,
    expectedVelocity: 2.8,
    revenueTotal: 2090000,
    revenueTotalUSD: 2090,
    comments: "Nocturno popular",
    tags: ["nocturno", "cama"],
  },
  {
    id: "srv-017",
    marketId: "bue-mza",
    marketName: "Buenos Aires - Mendoza",
    departureTime: "22:00",
    arrivalTime: "11:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 9,
    totalSeats: 45,
    soldSeats: 28,
    currentOccupancy: 62,
    targetOccupancy: 62,
    currentPrice: 52000,
    basePrice: 52000,
    recommendedPrice: 52500,
    priceChange: 1.0,
    status: "on-curve",
    gap: 0,
    bookingVelocity: 2.9,
    expectedVelocity: 2.8,
    revenueTotal: 1456000,
    revenueTotalUSD: 1456,
    comments: "",
    tags: ["nocturno"],
  },
  // Buenos Aires - Bariloche
  {
    id: "srv-018",
    marketId: "bue-brc",
    marketName: "Buenos Aires - Bariloche",
    departureTime: "10:00",
    arrivalTime: "06:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 21,
    totalSeats: 42,
    soldSeats: 40,
    currentOccupancy: 95,
    targetOccupancy: 65,
    currentPrice: 85000,
    basePrice: 75000,
    recommendedPrice: 98000,
    priceChange: 15.3,
    status: "ahead-3",
    gap: 30,
    bookingVelocity: 6.0,
    expectedVelocity: 2.5,
    revenueTotal: 3400000,
    revenueTotalUSD: 3400,
    comments: "Temporada ski",
    tags: ["cama", "suite", "premium", "top-seller"],
  },
  {
    id: "srv-019",
    marketId: "bue-brc",
    marketName: "Buenos Aires - Bariloche",
    departureTime: "18:00",
    arrivalTime: "14:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 18,
    totalSeats: 42,
    soldSeats: 35,
    currentOccupancy: 83,
    targetOccupancy: 65,
    currentPrice: 82000,
    basePrice: 75000,
    recommendedPrice: 90000,
    priceChange: 9.8,
    status: "ahead-2",
    gap: 18,
    bookingVelocity: 4.8,
    expectedVelocity: 2.5,
    revenueTotal: 2870000,
    revenueTotalUSD: 2870,
    comments: "",
    tags: ["cama", "suite"],
  },
  // Buenos Aires - Neuquén
  {
    id: "srv-020",
    marketId: "bue-neu",
    marketName: "Buenos Aires - Neuquén",
    departureTime: "09:00",
    arrivalTime: "23:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 11,
    totalSeats: 48,
    soldSeats: 34,
    currentOccupancy: 71,
    targetOccupancy: 60,
    currentPrice: 48000,
    basePrice: 45000,
    recommendedPrice: 52000,
    priceChange: 8.3,
    status: "ahead-2",
    gap: 11,
    bookingVelocity: 3.8,
    expectedVelocity: 2.8,
    revenueTotal: 1632000,
    revenueTotalUSD: 1632,
    comments: "Petróleo y turismo",
    tags: ["cama"],
  },
  {
    id: "srv-021",
    marketId: "bue-neu",
    marketName: "Buenos Aires - Neuquén",
    departureTime: "20:00",
    arrivalTime: "10:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 7,
    totalSeats: 48,
    soldSeats: 25,
    currentOccupancy: 52,
    targetOccupancy: 60,
    currentPrice: 44000,
    basePrice: 45000,
    recommendedPrice: 40000,
    priceChange: -9.1,
    status: "behind-1",
    gap: -8,
    bookingVelocity: 2.3,
    expectedVelocity: 2.8,
    revenueTotal: 1100000,
    revenueTotalUSD: 1100,
    comments: "",
    tags: ["nocturno"],
  },
  // Buenos Aires - Santa Fe
  {
    id: "srv-022",
    marketId: "bue-sfe",
    marketName: "Buenos Aires - Santa Fe",
    departureTime: "07:00",
    arrivalTime: "13:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 4,
    totalSeats: 52,
    soldSeats: 38,
    currentOccupancy: 73,
    targetOccupancy: 58,
    currentPrice: 22000,
    basePrice: 20000,
    recommendedPrice: 25000,
    priceChange: 13.6,
    status: "ahead-2",
    gap: 15,
    bookingVelocity: 4.2,
    expectedVelocity: 3.0,
    revenueTotal: 836000,
    revenueTotalUSD: 836,
    comments: "",
    tags: [],
  },
  {
    id: "srv-023",
    marketId: "bue-sfe",
    marketName: "Buenos Aires - Santa Fe",
    departureTime: "12:00",
    arrivalTime: "18:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 3,
    totalSeats: 52,
    soldSeats: 28,
    currentOccupancy: 54,
    targetOccupancy: 58,
    currentPrice: 19500,
    basePrice: 20000,
    recommendedPrice: 18500,
    priceChange: -5.1,
    status: "on-curve",
    gap: -4,
    bookingVelocity: 2.8,
    expectedVelocity: 3.0,
    revenueTotal: 546000,
    revenueTotalUSD: 546,
    comments: "",
    tags: [],
  },
  {
    id: "srv-024",
    marketId: "bue-sfe",
    marketName: "Buenos Aires - Santa Fe",
    departureTime: "17:00",
    arrivalTime: "23:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 5,
    totalSeats: 52,
    soldSeats: 18,
    currentOccupancy: 35,
    targetOccupancy: 58,
    currentPrice: 18000,
    basePrice: 20000,
    recommendedPrice: 14000,
    priceChange: -22.2,
    status: "behind-3",
    gap: -23,
    bookingVelocity: 1.4,
    expectedVelocity: 3.0,
    revenueTotal: 324000,
    revenueTotalUSD: 324,
    comments: "Muy baja demanda",
    tags: ["revisar", "promocionar"],
  },
  // Córdoba - Mendoza
  {
    id: "srv-025",
    marketId: "cor-mza",
    marketName: "Córdoba - Mendoza",
    departureTime: "08:00",
    arrivalTime: "16:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 9,
    totalSeats: 45,
    soldSeats: 36,
    currentOccupancy: 80,
    targetOccupancy: 60,
    currentPrice: 38000,
    basePrice: 35000,
    recommendedPrice: 44000,
    priceChange: 15.8,
    status: "ahead-3",
    gap: 20,
    bookingVelocity: 4.5,
    expectedVelocity: 2.8,
    revenueTotal: 1368000,
    revenueTotalUSD: 1368,
    comments: "Conexión interior",
    tags: ["semi-cama"],
  },
  {
    id: "srv-026",
    marketId: "cor-mza",
    marketName: "Córdoba - Mendoza",
    departureTime: "22:00",
    arrivalTime: "06:00",
    date: "2025-01-05",
    daysUntilDeparture: 12,
    ap: 6,
    totalSeats: 45,
    soldSeats: 28,
    currentOccupancy: 62,
    targetOccupancy: 60,
    currentPrice: 36000,
    basePrice: 35000,
    recommendedPrice: 37500,
    priceChange: 4.2,
    status: "on-curve",
    gap: 2,
    bookingVelocity: 3.0,
    expectedVelocity: 2.8,
    revenueTotal: 1008000,
    revenueTotalUSD: 1008,
    comments: "",
    tags: ["nocturno", "cama"],
  },
  // Más servicios para otras fechas
  {
    id: "srv-027",
    marketId: "bue-mdp",
    marketName: "Buenos Aires - Mar del Plata",
    departureTime: "06:00",
    arrivalTime: "11:30",
    date: "2025-01-06",
    daysUntilDeparture: 13,
    ap: 10,
    totalSeats: 52,
    soldSeats: 38,
    currentOccupancy: 73,
    targetOccupancy: 52,
    currentPrice: 27500,
    basePrice: 25000,
    recommendedPrice: 32000,
    priceChange: 16.4,
    status: "ahead-3",
    gap: 21,
    bookingVelocity: 4.8,
    expectedVelocity: 3.0,
    revenueTotal: 1045000,
    revenueTotalUSD: 1045,
    comments: "",
    tags: ["temporada-alta"],
  },
  {
    id: "srv-028",
    marketId: "bue-cor",
    marketName: "Buenos Aires - Córdoba",
    departureTime: "20:00",
    arrivalTime: "05:00",
    date: "2025-01-06",
    daysUntilDeparture: 13,
    ap: 16,
    totalSeats: 48,
    soldSeats: 40,
    currentOccupancy: 83,
    targetOccupancy: 55,
    currentPrice: 44000,
    basePrice: 38000,
    recommendedPrice: 52000,
    priceChange: 18.2,
    status: "ahead-3",
    gap: 28,
    bookingVelocity: 5.5,
    expectedVelocity: 2.8,
    revenueTotal: 1760000,
    revenueTotalUSD: 1760,
    comments: "",
    tags: ["nocturno", "cama", "top-seller"],
  },
  {
    id: "srv-029",
    marketId: "bue-mza",
    marketName: "Buenos Aires - Mendoza",
    departureTime: "18:00",
    arrivalTime: "07:00",
    date: "2025-01-06",
    daysUntilDeparture: 13,
    ap: 14,
    totalSeats: 45,
    soldSeats: 32,
    currentOccupancy: 71,
    targetOccupancy: 58,
    currentPrice: 54000,
    basePrice: 52000,
    recommendedPrice: 58000,
    priceChange: 7.4,
    status: "ahead-2",
    gap: 13,
    bookingVelocity: 4.2,
    expectedVelocity: 2.8,
    revenueTotal: 1728000,
    revenueTotalUSD: 1728,
    comments: "",
    tags: ["nocturno", "cama"],
  },
  {
    id: "srv-030",
    marketId: "bue-brc",
    marketName: "Buenos Aires - Bariloche",
    departureTime: "10:00",
    arrivalTime: "06:00",
    date: "2025-01-06",
    daysUntilDeparture: 13,
    ap: 22,
    totalSeats: 42,
    soldSeats: 38,
    currentOccupancy: 90,
    targetOccupancy: 62,
    currentPrice: 84000,
    basePrice: 75000,
    recommendedPrice: 95000,
    priceChange: 13.1,
    status: "ahead-3",
    gap: 28,
    bookingVelocity: 5.8,
    expectedVelocity: 2.5,
    revenueTotal: 3192000,
    revenueTotalUSD: 3192,
    comments: "Muy demandado",
    tags: ["cama", "suite", "premium", "top-seller"],
  },
]

function generateCurvePoints(
  baseOccupancy: number,
  tolerance: number,
): { daysBeforeDeparture: number; expectedOccupancy: number; toleranceLower: number; toleranceUpper: number }[] {
  const points = []
  // Key points at: 0, 1, 2, 3, 5, 7, 10, 14, 21, 30, 45, 60 days
  const keyDays = [0, 1, 2, 3, 5, 7, 10, 14, 21, 30, 45, 60]

  for (const day of keyDays) {
    // Occupancy curve: starts low and increases as departure approaches
    let expected: number
    if (day === 0)
      expected = 95 // Day of departure
    else if (day === 1) expected = 90
    else if (day === 2) expected = 85
    else if (day === 3) expected = 80
    else if (day <= 5) expected = 70
    else if (day <= 7) expected = 60
    else if (day <= 10) expected = 50
    else if (day <= 14) expected = 40
    else if (day <= 21) expected = 30
    else if (day <= 30) expected = 22
    else if (day <= 45) expected = 15
    else expected = 10

    // Adjust based on base occupancy target
    const adjustedExpected = Math.min(100, Math.round(expected * (baseOccupancy / 75)))

    points.push({
      daysBeforeDeparture: day,
      expectedOccupancy: adjustedExpected,
      toleranceLower: Math.max(0, adjustedExpected - tolerance),
      toleranceUpper: Math.min(100, adjustedExpected + tolerance),
    })
  }

  return points
}

export const fillingCurves: FillingCurve[] = [
  // Buenos Aires - Mar del Plata
  {
    id: "curve-bue-mdp-weekday",
    marketId: "bue-mdp",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(75, 5),
  },
  {
    id: "curve-bue-mdp-friday",
    marketId: "bue-mdp",
    pattern: "friday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(85, 5),
  },
  {
    id: "curve-bue-mdp-saturday",
    marketId: "bue-mdp",
    pattern: "saturday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(90, 5),
  },
  {
    id: "curve-bue-mdp-sunday",
    marketId: "bue-mdp",
    pattern: "sunday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(80, 5),
  },
  // Buenos Aires - Córdoba
  {
    id: "curve-bue-cor-weekday",
    marketId: "bue-cor",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(74, 5),
  },
  {
    id: "curve-bue-cor-friday",
    marketId: "bue-cor",
    pattern: "friday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(82, 5),
  },
  {
    id: "curve-bue-cor-saturday",
    marketId: "bue-cor",
    pattern: "saturday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(78, 5),
  },
  // Buenos Aires - Rosario
  {
    id: "curve-bue-ros-weekday",
    marketId: "bue-ros",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(72, 5),
  },
  {
    id: "curve-bue-ros-friday",
    marketId: "bue-ros",
    pattern: "friday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(80, 5),
  },
  // Buenos Aires - Mendoza
  {
    id: "curve-bue-mza-weekday",
    marketId: "bue-mza",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(78, 5),
  },
  {
    id: "curve-bue-mza-friday",
    marketId: "bue-mza",
    pattern: "friday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(88, 5),
  },
  // Buenos Aires - Bariloche
  {
    id: "curve-bue-brc-weekday",
    marketId: "bue-brc",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(80, 5),
  },
  {
    id: "curve-bue-brc-friday",
    marketId: "bue-brc",
    pattern: "friday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(92, 5),
  },
  // Buenos Aires - Neuquén
  {
    id: "curve-bue-neu-weekday",
    marketId: "bue-neu",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(70, 5),
  },
  // Buenos Aires - Santa Fe
  {
    id: "curve-bue-sfe-weekday",
    marketId: "bue-sfe",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(70, 5),
  },
  // Córdoba - Mendoza
  {
    id: "curve-cor-mza-weekday",
    marketId: "cor-mza",
    pattern: "weekday",
    zoneConfig: defaultZoneConfig,
    points: generateCurvePoints(72, 5),
  },
]

export const alerts: Alert[] = [
  {
    id: "alert-001",
    serviceId: "srv-024",
    serviceName: "Buenos Aires - Santa Fe 17:00",
    type: "occupation",
    severity: "critical",
    message: "Ocupación 23 puntos por debajo del objetivo. Velocidad de venta muy baja.",
    timestamp: "2025-01-01T10:30:00",
    acknowledged: false,
  },
  {
    id: "alert-002",
    serviceId: "srv-010",
    serviceName: "Buenos Aires - Córdoba 23:30",
    type: "occupation",
    severity: "critical",
    message: "Ocupación 20 puntos por debajo del objetivo. Considerar reducción de precio.",
    timestamp: "2025-01-01T09:15:00",
    acknowledged: false,
  },
  {
    id: "alert-003",
    serviceId: "srv-018",
    serviceName: "Buenos Aires - Bariloche 10:00",
    type: "demand",
    severity: "warning",
    message: "Alta demanda detectada. Oportunidad de optimización de precio (+15%).",
    timestamp: "2025-01-01T08:00:00",
    acknowledged: true,
  },
  {
    id: "alert-004",
    serviceId: "srv-001",
    serviceName: "Buenos Aires - Mar del Plata 06:00",
    type: "price",
    severity: "info",
    message: "Precio ajustado automáticamente de $27,000 a $28,500.",
    timestamp: "2024-12-31T22:00:00",
    acknowledged: true,
  },
  {
    id: "alert-005",
    serviceId: "srv-006",
    serviceName: "Buenos Aires - Mar del Plata 22:00",
    type: "occupation",
    severity: "warning",
    message: "Servicio nocturno 17 puntos por debajo. Evaluar promoción.",
    timestamp: "2025-01-01T11:00:00",
    acknowledged: false,
  },
]

export const alertRules: AlertRule[] = [
  {
    id: "rule-001",
    name: "Ocupación crítica baja",
    type: "occupation",
    condition: "below_target",
    threshold: 15,
    severity: "critical",
    enabled: true,
  },
  {
    id: "rule-002",
    name: "Ocupación baja",
    type: "occupation",
    condition: "below_target",
    threshold: 10,
    severity: "warning",
    enabled: true,
  },
  {
    id: "rule-003",
    name: "Alta demanda",
    type: "demand",
    condition: "velocity_above",
    threshold: 150,
    severity: "warning",
    enabled: true,
  },
]

export const aggressivenessConfig: AggressivenessConfig = {
  global: 5,
  marketOverrides: {
    "bue-brc": 7,
    "bue-mza": 6,
    "bue-sfe": 4,
  },
  safetyLimits: {
    maxPriceIncrease: 30,
    maxPriceDecrease: 25,
    minPrice: 8000,
    maxPrice: 120000,
  },
}

export const dashboardKPIs: DashboardKPIs = {
  totalRevenue: 2360000000,
  totalRevenueUSD: 2360000,
  revenueTarget: 2205000000,
  revenueTargetUSD: 2205000,
  revenueGrowth: 12.5,
  avgOccupancy: 72,
  occupancyTarget: 73,
  totalServices: 30,
  servicesOnTarget: 8,
  servicesBehind: 7,
  servicesAhead: 15,
  activeAlerts: 5,
  criticalAlerts: 2,
  totalPax: 945,
  totalSeats: 1432,
  totalFrequencies: 30,
}

export const revenueHistory: RevenueDataPoint[] = [
  {
    date: "Dic 26",
    revenue: 285000000,
    revenueUSD: 285000,
    target: 300000000,
    targetUSD: 300000,
    occupancy: 68,
    pax: 1250,
    seats: 1800,
    frequencies: 42,
  },
  {
    date: "Dic 27",
    revenue: 312000000,
    revenueUSD: 312000,
    target: 305000000,
    targetUSD: 305000,
    occupancy: 72,
    pax: 1380,
    seats: 1850,
    frequencies: 44,
  },
  {
    date: "Dic 28",
    revenue: 298000000,
    revenueUSD: 298000,
    target: 310000000,
    targetUSD: 310000,
    occupancy: 70,
    pax: 1320,
    seats: 1820,
    frequencies: 43,
  },
  {
    date: "Dic 29",
    revenue: 335000000,
    revenueUSD: 335000,
    target: 315000000,
    targetUSD: 315000,
    occupancy: 75,
    pax: 1450,
    seats: 1900,
    frequencies: 45,
  },
  {
    date: "Dic 30",
    revenue: 352000000,
    revenueUSD: 352000,
    target: 320000000,
    targetUSD: 320000,
    occupancy: 78,
    pax: 1520,
    seats: 1920,
    frequencies: 46,
  },
  {
    date: "Dic 31",
    revenue: 421000000,
    revenueUSD: 421000,
    target: 380000000,
    targetUSD: 380000,
    occupancy: 85,
    pax: 1780,
    seats: 2100,
    frequencies: 52,
  },
  {
    date: "Ene 1",
    revenue: 357000000,
    revenueUSD: 357000,
    target: 375000000,
    targetUSD: 375000,
    occupancy: 76,
    pax: 1540,
    seats: 2000,
    frequencies: 48,
  },
]
